### ISSUE TITLE
Correct the requirements.txt

### ISSUE THREAD

**Issue by sm18lr88** [UditGupta10/GPT-InvestAR#8]
I've been unable to set up the requirements.txt.
I've tried to manually go through each conda and each pip install and there are so many issues I encounter I've given up.
Python=3.9 got me the furthest, but still problematic.

It would be great if you maybe offered clearer list for users.

Thanks.

**Comment by UditGupta10** [comment]
I'd suggest to:
1. Use conda and start with a fresh env.
2. Create an env for openbb installation. Details can be found on their website.
3. Create a separate env for llama index. Refer its github page for installation.
4. Since the py files are separate for stock data loading and gpt based feature computation, these files can be run in respective environments.
5. I tried to install openbb and llama index in the same env myself but failed at that time, so I figured it's best to have separate envs for both.
